apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-test
  title: Test HTTP
  description: Try
spec:
  owner: oskar
  type: service
  steps:
    - id: backstage_request
      name: backstage re2quest
      action: http:backstage:request
      input:
        method: "GET"
        path: "/proxy/genderize/?name=test"
    - id: display_outputs
      name: Display Outputs
      action: debug:log
      input:
        message: "Probability: ${{ steps.backstage_request.output.body.probability }}"
  output:
    # These show as key/value items in the final summary
    name: ${{ steps.backstage_request.output.body.name }}
    gender: ${{ steps.backstage_request.output.body.gender }}
    probability: ${{ steps.backstage_request.output.body.probability }}

    # Optional: buttons at the bottom of the summary
    links:
      - title: Re-run query in Backstage proxy
        url: /proxy/genderize/?name=test
      - title: Genderize API (docs)
        url: https://genderize.io/
        icon: web
