apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-test
  title: Test HTTP
  description: Try
spec:
  owner: oskar
  type: service
  steps:
    - id: backstage_request
      name: backstage re2quest
      action: http:backstage:request
      input:
        method: "GET"
        path: "/proxy/genderize/?name=test"
    - id: display_outputs
      name: Display Outputs
      action: debug:log
      input:
        message: "Probability: ${{ steps.backstage_request.output.body | parseJson | get('probability') }}"
  output:
    text:
      - title: More information
        content: |
          **Entity URL:**`
